### ISSUE TITLE
fidb 

### ISSUE THREAD

**Issue by vanhauser-thc** [threatrack/ghidra-fidb-repo#1]
Can these directly copied into hidra/Features/FunctionID/data ?
The headers looks very different than the fidbf files there.
If they cant - why not create fidbf files?
If they can - that would be useful information in the README :)
thanks!

**Comment by 0x6d696368** [comment]
Added https://github.com/threatrack/ghidra-fidb-repo/blob/master/README.md#usage--installation

You can get the unpacked `*,fidbf` files from https://github.com/threatrack/ghidra-fidb-repo/releases/tag/20200530 to copy them to `Ghidra/Features/FunctionID/data`.

Hope this fixes your issue.
